"""phase3_unique_softdelete_collisions

Revision ID: 03dd511366e5
Revises: 
Create Date: 2026-09-17 01:37:04.814708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03dd511366e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eleves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_eleves_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('groupes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_groupes_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('inscriptions_groupes', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_inscription_eleve_groupe', ['eleve_id', 'groupe_id'])

    with op.batch_alter_table('paiements', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_paiement_eleve_groupe_mois', ['eleve_id', 'groupe_id', 'mois'])

    with op.batch_alter_table('presences', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_presence_eleve_groupe_date', ['eleve_id', 'groupe_id', 'date_seance'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presences', schema=None) as batch_op:
        batch_op.drop_constraint('uq_presence_eleve_groupe_date', type_='unique')

    with op.batch_alter_table('paiements', schema=None) as batch_op:
        batch_op.drop_constraint('uq_paiement_eleve_groupe_mois', type_='unique')

    with op.batch_alter_table('inscriptions_groupes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_inscription_eleve_groupe', type_='unique')

    with op.batch_alter_table('groupes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groupes_deleted_at'))
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('eleves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eleves_deleted_at'))
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
